### ISSUE TITLE
spid/acs response issue

### ISSUE THREAD

**Issue by Asifkrishaweb** [italia/spid-laravel#72]
i am actually testing the spid authentication in my local 8000 with 8088 testenv server

metadata of your sp, configured in spid-testenv2 :

<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8000/spid/acs" index="0" isDefault="true"/>

Where should i set this acs url :
in Spid-auth.php or spid-saml.php
in which parameter

please help form the same

i am outside of Italy so not able to join community

thank you

**Comment by pdavide** [comment]
Hi @ Asifkrishaweb,
you don't need to be in Italy in order to join the community, it's online! ;-)
Please follow this link https://slack.developers.italia.it/ and use the #spid channel for your help requests.

About your question, the acs URL doesn't need to be set in the configuration files because it is already defined as a route.
You need to verify that your metadata at  http://localhost:8000/spid/metadata is consistent with the SP config in spid-testenv-2.
